
x-ispn-image: &ispn_image infinispan/server:15.0.10.Final
x-kc-image: &kc_image quay.io/keycloak/keycloak:26.4.1
x-pg-image: &pg_image postgres:16

networks:
  vie-ispn: { driver: bridge }
  vie-kc: { driver: bridge }
  wan: { external: true }

volumes:
  vie_pgdata: {}
  vie-ispn-data-1: {}
  vie-ispn-data-2: {}
  vie-ispn-data-3: {}

services:
  vie-ispn-1:
    image: *ispn_image
    container_name: ispn-vie-1
    environment:
      USER: admin
      PASS: password
    networks:
      - vie-ispn
      - wan
    command: >
      -c infinispan-keycloak.xml
      -Dinfinispan.site.name=VIE
      -Dinfinispan.cluster.name=VIE-CLUSTER
      -Djgroups.mcast_addr=230.0.0.3
      -Djgroups.mcast_port=46656
      -Djgroups.bridge.mcast_addr=230.1.1.1
      -Djgroups.bridge.mcast_port=47655
    ports:
      - "31222:11222"
    volumes:
      - type: bind
        source: ../../common/infinispan-keycloak.xml
        target: /opt/infinispan/server/conf/infinispan-keycloak.xml
        read_only: true
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -fsS http://127.0.0.1:11222/rest/v2/cache-managers/default/health/status"]
      interval: 10s
      timeout: 3s
      retries: 30

  vie-ispn-2:
    image: *ispn_image
    container_name: ispn-vie-2
    environment:
      USER: admin
      PASS: password
    networks:
      - vie-ispn
      - wan
    command: >
      -c infinispan-keycloak.xml
      -Dinfinispan.site.name=VIE
      -Dinfinispan.cluster.name=VIE-CLUSTER
      -Djgroups.mcast_addr=230.0.0.3
      -Djgroups.mcast_port=46656
      -Djgroups.bridge.mcast_addr=230.1.1.1
      -Djgroups.bridge.mcast_port=47655
    ports:
      - "32222:11222"
    volumes:
      - type: bind
        source: ../../common/infinispan-keycloak.xml
        target: /opt/infinispan/server/conf/infinispan-keycloak.xml
        read_only: true
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -fsS http://127.0.0.1:11222/rest/v2/cache-managers/default/health/status"]
      interval: 10s
      timeout: 3s
      retries: 30

  vie-ispn-3:
    image: *ispn_image
    container_name: ispn-vie-3
    environment:
      USER: admin
      PASS: password
    networks:
      - vie-ispn
      - wan
    command: >
      -c infinispan-keycloak.xml
      -Dinfinispan.site.name=VIE
      -Dinfinispan.cluster.name=VIE-CLUSTER
      -Djgroups.mcast_addr=230.0.0.3
      -Djgroups.mcast_port=46656
      -Djgroups.bridge.mcast_addr=230.1.1.1
      -Djgroups.bridge.mcast_port=47655
    ports:
      - "33222:11222"
    volumes:
      - type: bind
        source: ../../common/infinispan-keycloak.xml
        target: /opt/infinispan/server/conf/infinispan-keycloak.xml
        read_only: true
    healthcheck:
      test: ["CMD", "bash", "-lc", "curl -fsS http://127.0.0.1:11222/rest/v2/cache-managers/default/health/status"]
      interval: 10s
      timeout: 3s
      retries: 30

  vie-pg:
    image: *pg_image
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes: [ "vie_pgdata:/var/lib/postgresql/data" ]
    networks: [ vie-kc ]

  vie-kc-1:
    image: *kc_image
    command:
      - start
      - --features=multi-site
      - --proxy-headers=xforwarded
      - --hostname-strict=false
      - --http-enabled=true
      - --https-port=8443
      - --https-certificate-file=/certs/edge.crt
      - --https-certificate-key-file=/certs/edge.key
    env_file: [ ./kc.env ]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: vie-pg
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_CACHE: ispn
      KC_CACHE_REMOTE_HOST: vie-ispn-1
      KC_CACHE_REMOTE_PORT: 11222
      KC_CACHE_REMOTE_USERNAME: admin
      KC_CACHE_REMOTE_PASSWORD: password
      KC_CACHE_REMOTE_TLS_ENABLED: "false"
      KC_SPI_CACHE_EMBEDDED_DEFAULT_SITE_NAME: "VIE"
      KC_HOSTNAME: login.vie.localhost
      KC_HTTP_PORT: 8080
    volumes:
      - ../../pki:/certs:ro
    depends_on: [ vie-ispn-1, vie-ispn-2, vie-ispn-3, vie-pg ]
    networks: [ vie-kc, vie-ispn, wan ]
    ports:
      - "9380:8080"

  vie-kc-2:
    image: *kc_image
    command:
      - start
      - --features=multi-site
      - --proxy-headers=xforwarded
      - --hostname-strict=false
      - --http-enabled=true
      - --https-port=8443
      - --https-certificate-file=/certs/edge.crt
      - --https-certificate-key-file=/certs/edge.key
    env_file: [ ./kc.env ]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: vie-pg
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_CACHE: ispn
      KC_CACHE_REMOTE_HOST: vie-ispn-2
      KC_CACHE_REMOTE_PORT: 11222
      KC_CACHE_REMOTE_USERNAME: admin
      KC_CACHE_REMOTE_PASSWORD: password
      KC_CACHE_REMOTE_TLS_ENABLED: "false"
      KC_SPI_CACHE_EMBEDDED_DEFAULT_SITE_NAME: "VIE"
      KC_HOSTNAME: login.vie.localhost
      KC_HTTP_PORT: 8080
    volumes:
      - ../../pki:/certs:ro
    depends_on: [ vie-ispn-1, vie-ispn-2, vie-ispn-3, vie-pg ]
    networks: [ vie-kc, vie-ispn, wan ]
    ports:
      - "9480:8080"
